version: '3.8'

services:
  api:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - ./music_controller/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
    

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
       - /app/node_modules

  postgres:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

volumes:
  postgres_data: